### ISSUE TITLE
例外処理とハンドリング

### ISSUE THREAD

**Issue by ys-practice** [hrnfujita/practice#2]
値が範囲外である場合にInputMismatchExceptionを明示的に発生させていますが、
これは運用を考えると微妙な作りと感じます。
理由としては
・入力値が数値でなかった場合
・入力値が想定範囲外であった場合
上記に対して同じエラーメッセージを吐くので発生原因の切り分けを
コードからたどる必要があるため監視運用で解決できずに開発者が出張ることになります。
せっかくバリデーションをしっかりと作りこまれているのであれば
nextIntだけをtry-catchし、想定範囲の値かどうかのif文は外だしして
それぞれメッセージを変えるなどすると良いかと思います。

https://github.com/hrnfujita/practice/blob/f214426cf88c03031993bce3427cb0353819a951/src/practice/WorldTime.java#L19-L27

**Comment by hrnfujita** [comment]
値の範囲チェックは外だししました。ありがとうございます。

**Comment by ys-practice** [comment]
確認しました。
